### PR TITLE
Clear up network questions

### LINKED ISSUE #230: MicroCloud init fails
I have been playing with microcloud setup for a while now.
I have three arm64 boards all with ubuntu core 22 images
2 Xilinx KV260 and a Mediatek board.

While the setup works fine .  But quite a few times it fails during `microcloud init` giving the following error

**Error: System "cobuntu" failed to join the cluster: Failed to update cluster status of services: Failed to join "LXD" cluster: LXD has already been initialized**

On the respective node(in this case **cobuntu**) if you check logs of microcloud daemon it gives following error.
`
Sep 30 12:48:50 cobuntu microcloud.daemon[1811]: time="2023-09-30T12:48:50Z" level=error msg="Failed to start server" err="accept tcp [::]:9443: use of closed network connection"
`
 @tomponline explained during product roadmap sprint 
The reason for this can be 
two different SOCs being used as nodes for cluster formation and xilinx boards being short on memory and processing power.
I was just rasing it here since I never observed CPU usage or memory usage exceeding boards limit .

`
lxd 5.19-31ff7b6 26096 latest/stable canonical** -
microceph 0+git.7b5672b 710 quincy/stable canonical** -
microcloud 1.1-04a1c49 737 latest/stable canonical** -
microovn 22.03.3+snap2d1a04de44 301 22.03/stable canonical** -

`

### PR DESCRIPTION
**Pull request by masnax**
Closes #230  

It's a bit hard to be descriptive, leave out OVN jargon, and keep the questions concise, but here's something a bit nicer.

### CODE REVIEW

**Comment by masnax** [comment]
This is assuming we do want to avoid referencing OVN concepts directly in the setup. If that's not a concern then we can have slightly longer descriptions that specifically inform about what the interfaces are going to be used for.

File: microcloud/cmd/microcloud/ask.go [hunk 1]
```diff
@@ -593,7 +593,7 @@ func (c *CmdControl) askNetwork(sh *service.Handler, systems map[string]InitSyst
 
 	// Uplink selection table.
 	header := []string{"LOCATION", "IFACE", "TYPE"}
-	fmt.Println("Select exactly one network interface from each cluster member:")
+	fmt.Println("Select exactly one interface per system to dedicate for the distributed network:")
```
Comment (roosterfish) [inline microcloud/cmd/microcloud/ask.go:596]: Maybe if we say "distributed overlay networks" it's even more clear that the actual virtual network traffic is meant? Just an idea :)

Comment (tomponline) [reply microcloud/cmd/microcloud/ask.go:596]: We need to mention that this interface is for traffic going between the overlay network and the ddyetbal uplink network. Otherwise it'll be understood its for intra cluster overlay traffic.

Comment (tomponline) [reply microcloud/cmd/microcloud/ask.go:596]: How about:

```
Select an available interface per system to provide external connectivity for distributed network(s)
```

Comment (roosterfish) [reply microcloud/cmd/microcloud/ask.go:596]: The egress traffic is also a valid point. +1 for the last suggestion.

Comment (tomponline) [reply microcloud/cmd/microcloud/ask.go:596]: Yeah, I used "external" as it could also be ingress too.

Comment (tomponline) [reply microcloud/cmd/microcloud/ask.go:596]: And I used "connectivity" to imply Internet access, but not specifically mandate it.

File: microcloud/cmd/microcloud/ask.go [hunk 2]
```diff
@@ -581,7 +581,7 @@ func (c *CmdControl) askNetwork(sh *service.Handler, systems map[string]InitSyst
 	}
 
 	if missingSystems {
-		wantsSkip, err := c.asker.AskBool("Some systems are ineligible for distributed networking. Continue anyway? (yes/no) [default=yes]: ", "yes")
+		wantsSkip, err := c.asker.AskBool("Some systems are missing an interface with no IPs assigned, or a bridge. Continue anyway? (yes/no) [default=yes]: ", "yes")
```
Comment (ru-fu) [inline microcloud/cmd/microcloud/ask.go:584]: I feel this is more ambiguous. It could be understood as "some systems are missing ..., or they are a bridge".
How about:
`Some systems are ineligible for distributed networking (they have neither an interface with no IPs assigned nor a bridge).`
It would be nicer to turn it around ("neither a bridge nor an interface with no IPs assigned"), but we probably want to put more emphasis on the interface with no IPs assigned?

File: microcloud/cmd/microcloud/ask.go (hunk 1 above)
Comment (ru-fu) [reply microcloud/cmd/microcloud/ask.go:596]: Should it be "network(s)"? The next questions mention "the distributed network".

**Review by ru-fu — COMMENTED** [review]
Can you do a search and replace on the docs as well, to fix the places where we mention the init questions?

File: microcloud/cmd/microcloud/ask.go (hunk 1 above)
Comment (tomponline) [reply microcloud/cmd/microcloud/ask.go:596]: The user is selecting an interface for use by the distributed network(s) for external connectivity.
The init process is setting up one initial distributed network, but the user can add more in the future (thats one of the big benefits of OVN).

File: microcloud/cmd/microcloud/ask.go (hunk 2 above)
Comment (masnax) [reply microcloud/cmd/microcloud/ask.go:584]: The double negative might be confusing as well. 
How is: 
```
Some systems are ineligible for distributed networking: Requires (1) an interface with no IPs assigned or (2) a bridge. Continue anyway? (yes/no) [default=yes]
```

**Comment by masnax** [comment]
Also added a commit that should clear up the error from #230

File: microcloud/cmd/microcloud/ask.go (hunk 2 above)
Comment (ru-fu) [reply microcloud/cmd/microcloud/ask.go]:
```
Some systems are ineligible for distributed networking, which requires either an interface with no IPs assigned or a bridge. Continue anyway? (yes/no) [default=yes]
```
I see why you're using the numbers to make the alternatives clear, but they would prompt me to type either 1 or 2 instead of "yes".

File: microcloud/cmd/microcloud/ask.go [hunk 3]
```diff
@@ -581,7 +581,7 @@ func (c *CmdControl) askNetwork(sh *service.Handler, systems map[string]InitSyst
 	}
 
 	if missingSystems {
-		wantsSkip, err := c.asker.AskBool("Some systems are ineligible for distributed networking. Continue anyway? (yes/no) [default=yes]: ", "yes")
+		wantsSkip, err := c.asker.AskBool("Some systems are ineligible for distributed networking: Requires (1) an interface with no IPs assigned or (2) a bridge. Continue anyway? (yes/no) [default=yes]: ", "yes")
```
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/cmd/microcloud/ask.go]: Thanks!

**Comment by masnax** [comment]
@ru-fu docs should now be updated as well.

**Review by ru-fu — DISMISSED** [review]
Thank you!

File: doc/tutorial/get_started.rst [hunk 4]
```diff
@@ -400,8 +400,8 @@ See the full initialisation process here:
     Using "enp6s0" on "micro4" for OVN uplink
 
    Specify the IPv4 gateway (CIDR) on the uplink network (empty to skip IPv4): 192.0.2.1/24
-   Specify the first IPv4 address in the range to use with LXD: 192.0.2.100
-   Specify the last IPv4 address in the range to use with LXD: 192.0.2.254
+   Specify the first IPv4 address in the range to use for the distributed network(s): 192.0.2.100
```
[the remark this answers is not in the document]
Comment (ru-fu) [reply doc/tutorial/get_started.rst:403]: Only if we also change it in the code.

[the remark this answers is not in the document]
Comment (masnax) [reply doc/tutorial/get_started.rst:403]: The previous question just says "specify the gateway (CIDR) on the uplink network" and this whole block starts with "Do you want to set up distributed networks?" so I think it might be less of a mouthful if we just say

`Specify the {first/last} {ipv4/ipv6} address in the range to use on the uplink network`

[the remark this answers is not in the document]
Comment (ru-fu) [reply doc/tutorial/get_started.rst]: I actually find Tom's version clearer - yes, it's long and a bit repetitive, but for me who has no clue about networks, this makes it clear that okay, I'm now creating the distributed network, and I need to specify and address on the uplink network.

**Review by tomponline — APPROVED** [review]
