### PR TITLE
Reuse existing MicroCeph and MicroOVN clusters

### LINKED ISSUE #145: Handle MicroCeph already installed
I have MicroCeph installed independently, before MicroCloud to use a dedicated network. When asked during the MicroCloud install if I want distributed storage, I say "no", but there seems to be an internal assumption preventing the setup to complete.

```
Would you like to set up distributed storage? (yes/no) [default=yes]: no

Configure distributed networking? (yes/no) [default=yes]: 
Select exactly one network interface from each cluster member:

 Using "enp6s0" on "n2" for OVN uplink
 Using "enp6s0" on "n1" for OVN uplink
 Using "enp6s0" on "n3" for OVN uplink

Specify the IPv4 gateway (CIDR) on the uplink network (empty to skip IPv4): 192.168.10.1/24
Specify the first IPv4 address in the range to use with LXD: 192.168.10.100
Specify the last IPv4 address in the range to use with LXD: 192.168.10.200
Specify the IPv6 gateway (CIDR) on the uplink network (empty to skip IPv6): 
Initializing a new cluster
 Local MicroCloud is ready
 Local LXD is ready
 Local MicroOVN is ready
Error: Failed to bootstrap local MicroCeph: Failed to initialize local remote entry: A remote with name "n1" already exists
```

### PR DESCRIPTION
**Pull request by masnax**
Closes #145

This PR allows initializing a new MicroCloud with some nodes that have already set up MicroCeph or MicroOVN in the past. This can be useful if you already have a MicroCeph cluster for example, that you want to "upgrade" into a MicroCloud.

Just after confirming the list of systems to use for the MicroCloud, we will try to grab a list of cluster members from each system. The underlying microcluster package will either return the list or report that the database is not initialized. We will record the first list that we obtain for each of MicroOVN and MicroCeph, and if the list is either non-existent or identical across any other systems, we can try to reuse those clusters.

The reuse process basically amounts to asking the system that has an existing cluster to generate join tokens and send them to the node orchestrating the initialization. Normally you have to be trusted to make such a request, so instead we can use the auth secret that we got from finding the systems over mDNS to send a request using the MicroCloud proxy, which will initiate the request from the unix socket on the clustered system.

The behaviour is as follows:
* If two systems belong to different clusters for the same service, we will error out as they wouldn't be able to join each other.
* If a cluster contains more nodes than what will end up in the MicroCloud, we will proceed as normal and ignore those nodes. Perhaps a user might want a larger MicroCeph cluster than their LXD cluster, for example.
* If `--auto` is specified, we will strictly require no clustered systems.
* The preseed file will have a new key `reuse_existing_clusters` which can be set to true or false. If true, we will reuse any clusters we find, and if false, we will skip that service entirely and set up as normal.
* In interactive mode, we will prompt the user for each service whether they want to reuse the existing cluster or setup MicroCloud without that service.

### CODE REVIEW

File: microcloud/service/microcloud.go [hunk 1]
```diff
@@ -95,6 +97,26 @@
...
 
+// RemoteIssueToken issues a token for the given peer on a remote MicroCloud where we are authorized by mDNS.
+func (s CloudService) RemoteIssueToken(ctx context.Context, clusterAddress string, secret string, peer string, serviceType types.ServiceType) (string, error) {
+	c, err := s.client.RemoteClient(util.CanonicalNetworkAddress(clusterAddress, CloudPort))
+	if err != nil {
+		return "", err
+	}
+
+	c.Client.Client.Transport = &http.Transport{
+		TLSClientConfig:   &tls.Config{InsecureSkipVerify: true},
```
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/service/microcloud.go:108]: We use `InsecureSkipVerify` in MicroCloud so that we can instead authenticate with the mDNS secret prior to setting up the cluster.

**Comment by masnax** [comment]
@markylaing @roosterfish @tomponline 

This one should be ready for review now.

**Comment by tomponline** [comment]
Thanks @masnax 

Once @markylaing and @roosterfish have approved ill do  a final pass. Ta

File: microcloud/cmd/microcloud/main_init.go [hunk 2]
```diff
@@ -368,8 +351,9 @@ func waitForJoin(sh *service.Handler, clusterSize int, secret string, peer strin
 				return err
 			}
 
-			if len(systems) == clusterSize+1 {
+			if len(systems) == clusterSize[service]+1 {
 				delete(clustered, service)
+				clusterSize[service] = clusterSize[service] + 1
```
Comment (roosterfish) [inline microcloud/cmd/microcloud/main_init.go:356]: I fear I don't quite get what this is doing. Could you please add a comment?

**Review by roosterfish — CHANGES_REQUESTED** [review]
Looks good to me, only a few smaller suggestions.

File: microcloud/service/microceph.go [hunk 3]
```diff
@@ -131,10 +133,33 @@ func (s CephService) Join(ctx context.Context, joinConfig JoinConfig) error {
...
+func (s CephService) ClusterMembers(ctx context.Context, info *mdns.ServerInfo) (map[string]string, error) {
+	var client *client.Client
+	var err error
+	if info != nil && info.Name != s.name {
+		client, err = s.m.RemoteClient(util.CanonicalNetworkAddress(info.Address, CloudPort))
+		if err != nil {
+			return nil, err
+		}
+
+		client.Client.Client.Transport = &http.Transport{
```
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/service/microceph.go:146]: I'll have a PR coming soon that gets rid of these entirely, thanks to https://github.com/canonical/microcluster/pull/83

To keep this PR simple I've maintained the pre-existing behaviour. There's actually a few significant refactors that need to be made to the client generation in MicroCloud because we inefficiently open clients all over the place. I've been thinking of maintaining a map of clients in memory so that we don't need to constantly instantiate new ones throughout the init process.

File: microcloud/cmd/microcloud/main_init.go [hunk 4]
```diff
@@ -414,6 +421,76 @@ func AddPeers(sh *service.Handler, systems map[string]InitSystem) error {
...
 }
 
+// checkClustered checks whether any of the selected systems have already initialized a service.
+func checkClustered(s *service.Handler, autoSetup bool, serviceType types.ServiceType, systems map[string]InitSystem) (string, map[string]string, error) {
+	var firstInitializedSystem string
+	var existingMembers map[string]string
+
+	// We don't allow appending to an existing LXD cluster.
+	if serviceType == types.LXD {
+		return "", nil, nil
```
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:478]: When MicroCloud first starts, it already checks whether LXD is initialized before it restarts LXD [here](https://github.com/canonical/microcloud/blob/81d501c885e4fd559842b2654714672f667d55d0/microcloud/cmd/microcloud/main_init.go#L89) to ensure the correct symlinks to MicroOVN and MicroCeph are present. We do this so we don't accidentally restart LXD while it's running instances for example.

This condition is just a convenience that lets us exit early from the `checkClustered` function in the case of LXD because it will always be uninitialized if we got to this point. 

I thought it might keep the invocation simple since we can just iterate over every `serviceType` and call `checkClustered` for all of them and get a sane value. The alternative would be that we need to remember to always call `checkClustered` in an if block where `serviceType != types.LXD`.

File: microcloud/service/microceph.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (roosterfish) [reply microcloud/service/microceph.go:146]: Ok, thanks for the details and the link. Fine for me then.

File: microcloud/cmd/microcloud/main_init.go (hunk 2 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:356]: Sure, I'll add a comment too, but it's basically just ensuring that the after a node joins a service (the call to `cloud.RequestJoin`), that we actually wait until the node is present in the corresponding daemon's database by checking that the cluster size has actually been incremented. 

We repeat this check until the cluster member appears (the number of rows in the table increases), at which point we can delete the service from the `clustered` list so we don't need to check it in the next loop, and we update the expected size of the cluster so that the next node that joins is checked against the updated cluster size.

File: microcloud/cmd/microcloud/main_init.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (roosterfish) [reply microcloud/cmd/microcloud/main_init.go:478]: >  because it will always be uninitialized if we got to this point.

I was not thinking about this, thanks, clear now! I think it would be helpful to extend the comment with the reason why an empty string is returned here.

File: microcloud/cmd/microcloud/main_init.go (hunk 2 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:356]: It might be helpful here to remember that `RequestJoin` will attempt join 1 node to all services concurrently, so we iterate over all services until the cluster_members table reflects the change. 

This is so we don't get into a weird situation where dqlite somehow mishandles 2 nodes concurrently joining.

File: microcloud/cmd/microcloud/main_init.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:481]: Updated the comment and labelled the args so it should be a bit clearer now. Don't know why the preview is still showing the old version.

File: microcloud/cmd/microcloud/main_init.go (hunk 2 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:361]: Added a commit which comments all the behaviours in this block.

Comment (roosterfish) [reply microcloud/cmd/microcloud/main_init.go:361]: I see so `len(systems)` is incremented by 1 as soon as the node has joined for the respective service.
And since `clusterSize` is a map you increment the reference here so that follow up calls to `waitForJoin` use the updated value.

**Comment by masnax** [comment]
@markylaing @tomponline Do either of you want to take a look at this before merging?

Also @ru-fu Looks like there's something going on with the doc checks here. Got any ideas?

**Comment by markylaing** [comment]
> @markylaing @tomponline Do either of you want to take a look at this before merging?
> 
> Also @ru-fu Looks like there's something going on with the doc checks here. Got any ideas?

Yes I'd like to take a look. Will get to it first thing tomorrow.

**Comment by ru-fu** [comment]
This sounds like it needs doc updates.

**Comment by markylaing** [comment]
> * The preseed file will have a new key `reuse_existing_clusters` which can be set to true or false. If true, we will reuse any clusters we find, and if false, we will skip that service entirely and set up as normal.

If this key is false, does it error out if we find existing Ceph or OVN clusters as it does with the `--auto` flag? I'm presuming here that we can't set up a new Ceph or OVN cluster on top of one that pre-exists.

File: microcloud/service/microceph.go [hunk 5]
```diff
@@ -131,10 +133,33 @@ func (s CephService) Join(ctx context.Context, joinConfig JoinConfig) error {
 }
 
 // ClusterMembers returns a map of cluster member names and addresses.
-func (s CephService) ClusterMembers(ctx context.Context) (map[string]string, error) {
-	client, err := s.Client("", "")
-	if err != nil {
-		return nil, err
+// Optionally sends a remote request using the information in ServerInfo.
+func (s CephService) ClusterMembers(ctx context.Context, info *mdns.ServerInfo) (map[string]string, error) {
```
Comment (markylaing) [inline microcloud/service/microceph.go:137]: Same here, I think it would be clearer to have a separate function when we want to use the remote client.

File: microcloud/service/microcloud.go [hunk 6]
```diff
@@ -95,6 +95,26 @@ func (s CloudService) IssueToken(ctx context.Context, peer string) (string, erro
...
+		DisableKeepAlives: true,
+		Proxy: func(r *http.Request) (*url.URL, error) {
+			r.Header.Set("X-MicroCloud-Auth", secret)
+
+			return shared.ProxyFromEnvironment(r)
+		},
+	}
```
[the remark this answers is not in the document]
Comment (markylaing) [reply microcloud/service/microcloud.go:115]: I've just seen this https://github.com/canonical/microcloud/pull/259/commits/b9479a9645ac45ec5634991810561fa73ade4ec1#r1559631449 so ignore this comment :)

File: microcloud/cmd/microcloud/ask.go [hunk 7]
```diff
@@ -816,3 +817,44 @@ func (c *CmdControl) askNetwork(sh *service.Handler, systems map[string]InitSyst
...
+	}
+
+	for serviceType := range expectedServices {
+		initializedSystem, err := checkClustered(s, autoSetup, serviceType, systems)
+		if err != nil {
+			return err
+		}
+
+		if initializedSystem != "" {
+			question := fmt.Sprintf("%q is already part of a %s cluster. Use this cluster to MicroCloud, or skip %s? (reuse/skip) [default=reuse]", initializedSystem, serviceType, serviceType)
```
Comment (markylaing) [inline microcloud/cmd/microcloud/ask.go]: The wording here is a bit off. Perhaps:
```golang
fmt.Sprintf("%q is already part of a %s cluster. Do you want to add this cluster to Microcloud? (add/skip) [default=add]", initializedSystem, serviceType)
```

Also, do we need to capitalise or otherwise format the `serviceType` string?

File: microcloud/cmd/microcloud/ask.go [hunk 8]
```diff
@@ -830,13 +830,13 @@ func (c *CmdControl) askClustered(s *service.Handler, autoSetup bool, systems ma
...
 	for serviceType := range expectedServices {
-		initializedSystem, err := checkClustered(s, autoSetup, serviceType, systems)
+		initializedSystem, _, err := checkClustered(s, autoSetup, serviceType, systems)
 		if err != nil {
 			return err
 		}
 
 		if initializedSystem != "" {
-			question := fmt.Sprintf("%q is already part of a %s cluster. Use this cluster to MicroCloud, or skip %s? (reuse/skip) [default=reuse]", initializedSystem, serviceType, serviceType)
+			question := fmt.Sprintf("%q is already part of a %s cluster. Use this cluster with MicroCloud, or skip %s? (reuse/skip) [default=reuse]: ", initializedSystem, serviceType, serviceType)
```
Comment (markylaing) [inline microcloud/cmd/microcloud/ask.go:839]: Should these changes be in the previous commit?

File: microcloud/cmd/microcloud/main_init.go [hunk 9]
```diff
@@ -327,33 +327,16 @@ func lookupPeers(s *service.Handler, autoSetup bool, iface *net.Interface, subne
...
-		cfg.Tokens = append(cfg.Tokens, types.ServiceToken{Service: s.Type(), JoinToken: token})
-		mut.Unlock()
-
-		return nil
-	})
-	if err != nil {
-		return err
-	}
-
+func waitForJoin(sh *service.Handler, clusterSize map[types.ServiceType]int, secret string, peer string, cfg types.ServicesPut) error {
```
Comment (markylaing) [inline microcloud/cmd/microcloud/main_init.go:330]: Three functions have been changed in this commit, could you please add a commit for each change with a comment describing the reason for the change. E.g. This function no longer issues a token, why was it moved to `AddPeers`?

File: microcloud/service/microcloud.go [hunk 10]
```diff
@@ -127,19 +127,28 @@ func (s CloudService) RequestJoin(ctx context.Context, secret string, name strin
...
+			TLSClientConfig:   &tls.Config{InsecureSkipVerify: true},
+			DisableKeepAlives: true,
+			Proxy: func(r *http.Request) (*url.URL, error) {
+				r.Header.Set("X-MicroCloud-Auth", secret)
 
-			return shared.ProxyFromEnvironment(r)
-		},
+				return shared.ProxyFromEnvironment(r)
+			},
+		}
```
Comment (markylaing) [inline microcloud/service/microcloud.go:151]: Now that https://github.com/canonical/microcluster/pull/83 is merged does this need to be updated? Same for the other cases where this is being set.

File: microcloud/cmd/microcloud/main_init_preseed.go [hunk 11]
```diff
@@ -391,6 +392,22 @@ func (p *Preseed) Parse(s *service.Handler, bootstrap bool) (map[string]InitSyst
...
+
+	for serviceType := range expectedServices {
+		initializedSystem, _, err := checkClustered(s, false, serviceType, systems)
+		if err != nil {
+			return nil, err
+		}
+
+		if initializedSystem != "" && !p.ReuseExistingClusters {
+			delete(s.Services, serviceType)
+		}
```
Comment (markylaing) [inline microcloud/cmd/microcloud/main_init_preseed.go:408]: I'm not sure if we should error out here or not. I wouldn't expect ceph to be running on a LXD cluster member unless it was being used in the that LXD cluster, so for me this would be indicative of misconfiguration.

File: microcloud/test/includes/microcloud.sh [hunk 12]
```diff
@@ -287,7 +287,7 @@ validate_system_lxd_ovn() {
 
   # Check that the created UPLINK network has the right DNS servers.
   if [ -n "${dns_namesersers}" ] ; then
-    dns_addresses=$(lxc exec "${name}" -- sh -c "lxc network get UPLINK dns.nameservers")
+    dns_addresses=$(lxc exec "local:${name}" -- sh -c "lxc network get UPLINK dns.nameservers")
```
Comment (markylaing) [inline microcloud/test/includes/microcloud.sh:290]: Is this commit specific to this PR or can it be moved into a different one?

File: microcloud/cmd/microcloud/main_init.go [hunk 13]
```diff
@@ -339,18 +339,23 @@ func waitForJoin(sh *service.Handler, clusterSize map[types.ServiceType]int, sec
...
+		// Check the size of the cluster for each service.
 		for service := range clustered {
 			systems, err := sh.Services[service].ClusterMembers(context.Background(), nil)
 			if err != nil {
 				return err
 			}
 
+			// If the size of the cluster has been incremented by 1 from its initial value,
+			// then we don't need to check the corresponding service anymore.
+			// So remove the service from consideration and update the current cluster size for the next node.
```
Comment (markylaing) [inline microcloud/cmd/microcloud/main_init.go:358]: Perhaps this should be in the previous commit which edited the `waitForJoin` function?

**Review by markylaing — CHANGES_REQUESTED** [review]
I think the structure of it looks good but some parts could be made a bit clearer.

Also, one concern I have with this is the reliance on mDNS for issuing the tokens. Will it be possible to add existing services if the join process changes such that explicit verification is required on both ends? I believe @roosterfish is working on this currently so I think it's worth a discussion around that.

**Comment by tomponline** [comment]
> @markylaing @tomponline Do either of you want to take a look at this before merging?

I'll look over once approved by the others.

**Comment by roosterfish** [comment]
> Also, one concern I have with this is the reliance on mDNS for issuing the tokens. Will it be possible to add existing services if the join process changes such that explicit verification is required on both ends? 

Good point, I have also thought about this the other day when reviewing the PR. Essentially what we will probably not have anymore is the secret used for the `X-MicroCloud-Auth` header to talk to the other MicroCloud daemon. 
So it has to be an action invoked by the administrator on the target system. 
I have it on my list of things for the spec so we can discuss it there :)

**Comment by tomponline** [comment]
> Also, one concern I have with this is the reliance on mDNS for issuing the tokens. Will it be possible to add existing services if the join process changes such that explicit verification is required on both ends? I believe @roosterfish is working on this currently so I think it's worth a discussion around that.

It will almost certainly have to change as mdns isn't going to be used as much. But that shouldn't necessarily block this PR - although it will likely have to be reworked as part of @roosterfish planned changes.

**Comment by masnax** [comment]
> Also, one concern I have with this is the reliance on mDNS for issuing the tokens. Will it be possible to add existing services if the join process changes such that explicit verification is required on both ends? I believe @roosterfish is working on this currently so I think it's worth a discussion around that.

At the moment, pretty much everything MicroCloud does requires mDNS to work because we can't be trusted on the other systems until we've clustered with them. We need mDNS for selecting disks, selecting networks, and selecting the nodes themselves, and now issuing tokens from existing clusters with this PR. 

I'd assume the verification process would establish a long-lived trust for the duration of the join process similar to the mDNS auth secret, allowing us to remotely issue tokens, view available disks and network interfaces, and request a node to join the clusters.

**Comment by masnax** [comment]
> > I'd assume the verification process would establish a long-lived trust for the duration of the join process similar to the mDNS auth secret, allowing us to remotely issue tokens, view available disks and network interfaces, and request a node to join the clusters.
> 
> An option I am trying to validate for the spec is moving the forming of the MicroCloud MicroCluster right after the discovery of new peers. This establishes trust between all the peers and allow them talking to each other using mutual TLS to perform the actions we are currently performing using the auth secret.
> 
> With this approach we don't anymore require any type of auth secret besides a join token for each of the peers that want to join the MicroCloud.

For some historical context, we actually had a similar process in place very early on because I was hesitant to rely on the mDNS component so much. 

Problem was mainly user experience. 90% of errors will happen around the configuration so a mistake would be costly as we would have to tear down the clusters. Plus it puts a significant pause (could be minutes for larger clusters) before we even get to the bulk of the user interactions.

File: microcloud/cmd/microcloud/main_init_preseed.go (hunk 11 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init_preseed.go:408]: It's tough since MicroCeph/MicroOVN might have other applications besides LXD. 

If we error out, that's like saying "you can't have a MicroCloud with these systems until you fundamentally change your current MicroCeph cluster". If we don't error out, it's "You can still have a MicroCloud, but it won't include MicroCeph until you fundamentally change your current MicroCeph cluster".

Since MicroCeph and MicroOVN are optional for MicroCloud, I think the second one makes sense and the first is too restrictive. PR #260 which builds on this PR will allow for adding MicroCeph/MicroOVN to MicroCloud if it was optionally/implicitly skipped before.

**Comment by roosterfish** [comment]
> 90% of errors will happen around the configuration so a mistake would be costly as we would have to tear down the clusters. Plus it puts a significant pause (could be minutes for larger clusters) before we even get to the bulk of the user interactions.

What do you mean by we have to tear down the clusters? 

If I understood you right you are talking about the pause which will be an effect of joining in the cluster members manually? I guess this is something we have to accept as part of making the overall concept more secure. But it's worth evaluating options to make this as fast as possible for the end user.

**Comment by masnax** [comment]
> What do you mean by we have to tear down the clusters?
The user runs `microcloud init`, but mistakenly hasn't prepared disks/network interfaces appropriately yet. If the systems are clustered before we ask the storage/network questions, the user only realizes the mistake after the nodes have been clustered. Now aborting the init process so the user can fix the mistake becomes much more expensive because we have already changed state on every system, before the user has made any choices.

File: microcloud/service/lxd.go [hunk 14]
```diff
@@ -225,8 +225,16 @@ func (s LXDService) IssueToken(ctx context.Context, peer string) (string, error)
 }
 
 // ClusterMembers returns a map of cluster member names and addresses.
-func (s LXDService) ClusterMembers(ctx context.Context) (map[string]string, error) {
-	client, err := s.Client(ctx, "")
+// Optionally sends a remote request using the information in ServerInfo.
+func (s LXDService) ClusterMembers(ctx context.Context, info *mdns.ServerInfo) (map[string]string, error) {
```
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/service/lxd.go]: I've added `RemoteClusterMembers` to do this now.

File: microcloud/cmd/microcloud/ask.go (hunk 7 above)
Comment (masnax) [reply microcloud/cmd/microcloud/ask.go]: No, the type represents consrs which are actual service names, capitalized appropriately. So `MicroCloud`, `MicroOVN`, `MicroCeph`, `LXD`.

File: microcloud/cmd/microcloud/ask.go (hunk 8 above)
Comment (masnax) [reply microcloud/cmd/microcloud/ask.go]: Oops, bad squash.

File: microcloud/cmd/microcloud/main_init.go (hunk 9 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:330]: I've split it up now and added some more info in the commit message. 

Basically I thought that since the token issuing process was becoming more complex, and `AddPeers` was going to handle other components of the existing-cluster detection, it made more sense to move all the related logic over there and keep `waitForJoin` to strictly request a join and wait for it to complete.

File: microcloud/test/includes/microcloud.sh (hunk 12 above)
Comment (masnax) [reply microcloud/test/includes/microcloud.sh]: Removed it.

File: microcloud/service/microcloud.go (hunk 10 above)
Comment (masnax) [reply microcloud/service/microcloud.go:150]: Instead of filling this PR with all of those changes, I've added a new PR that moves all this implementation into a helper so we can just call that instead: #287

**Comment by masnax** [comment]
Rebased.

File: microcloud/cmd/microcloud/main_init_preseed.go (hunk 11 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init_preseed.go:415]: I've also added a warning that the service will be skipped now, so the user is aware of it.

**Comment by masnax** [comment]
@roosterfish @markylaing Could you two please give this PR another look-over? Thanks!

**Comment by roosterfish** [comment]
> @roosterfish @markylaing Could you two please give this PR another look-over? Thanks!

Is the pipeline expected to fail or waiting on other PRs?

**Comment by masnax** [comment]
> > @roosterfish @markylaing Could you two please give this PR another look-over? Thanks!
> 
> Is the pipeline expected to fail or waiting on other PRs?

Ah yeah the fix for the tests has been merged now, so I've just rebased to re-run them (though the test suite is still unreliable so there may be some expected failures).

**Comment by masnax** [comment]
OK, had to make 2 small changes:

* `ReuseExistingCluster` is explicitly blocked on `microcloud add --preseed` because there's too much complexity to consider when accommodating all the existing nodes into the joining node's pre-existing cluster. Instead there's #260 which should facilitate this.

* Fixed a bug introduced into `microcloud add` which wasn't correctly considering the cluster size when joining new nodes: https://github.com/canonical/microcloud/pull/259/files#diff-a0869b68249cc46dfcc32cb652f562f713b0711198ccff1bd0cc7b5a47d7fbb0R436-R443

**Comment by roosterfish** [comment]
The new `test_reuse_cluster()` test is failing right at the beginning. From the output it looks it uses some wrong values for the question/answer dialog.

File: microcloud/cmd/microcloud/main_init.go [hunk 15]
```diff
@@ -333,32 +333,38 @@ func lookupPeers(s *service.Handler, autoSetup bool, iface *net.Interface, subne
 // waitForJoin issues a token and instructs a system to request a join,
```
Comment (markylaing) [inline microcloud/cmd/microcloud/main_init.go:333]: Looks like the comment needs to be updated as it no longer issues a token.

File: microcloud/cmd/microcloud/main_init.go [hunk 16]
```diff
@@ -333,32 +333,38 @@ func lookupPeers(s *service.Handler, autoSetup bool, iface *net.Interface, subne
...
 // and then waits for the request to either complete or time out.
 // If the request was successful, it additionally waits until the cluster appears in the database.
-func waitForJoin(sh *service.Handler, clusterSize int, secret string, peer string, cfg types.ServicesPut) error {
+func waitForJoin(sh *service.Handler, clusterSize map[types.ServiceType]int, secret string, peer string, cfg types.ServicesPut) error {
```
Comment (markylaing) [inline microcloud/cmd/microcloud/main_init.go:336]: Similarly, the `clusterSize` variable no longer describes what the variable is.

**Review by markylaing — CHANGES_REQUESTED** [review]
Just a couple of nits but otherwise looks good :+1: 

Tests are failing though :cry:

**Comment by masnax** [comment]
Test issues were just an incorrect parameter (I was passing `reuse` to the new question instead of `add` which was suggested in review).

**Comment by masnax** [comment]
@ru-fu I've added a commit that documents this feature (and another related feature in a bit more detail). I'm not sure if this is quite the right place so if you have any ideas I'd be happy to hear them :)

https://github.com/canonical/microcloud/pull/259/commits/2ad62dd4af6f8d9a9069110b68267d98c0884149

**Comment by masnax** [comment]
Another odd error with the test suite: https://github.com/canonical/microcloud/actions/runs/8822867943/job/24222020581?pr=259#step:9:8673

This should be `lxd_disk1`, so that means 1 of 2 things happened:
* The sorting of `lxc info --resources` doesn't necessarily match up with the ID given to the disk.

* Somehow the disk wasn't reset properly. This one would be really weird since we manually destroy and add back the volumes between each test, before we restore from the snapshot that was taken during the initial setup of the test suite.

@simondeziel Maybe we should add something like
```bash
lxc exec "${name}" -- lxc query "/1.0/resources" | jq -r '.storage.disks[] | {id, device_id, device_path}'
```

during `validate_system_lxd` before we validate storage so that we can catch it if it happens again?

**Comment by simondeziel** [comment]
> Another odd error with the test suite: https://github.com/canonical/microcloud/actions/runs/8822867943/job/24222020581?pr=259#step:9:8673

That's the exact error I often ran into.

> @simondeziel Maybe we should add something like
> 
> ```shell
> lxc exec "${name}" -- lxc query "/1.0/resources" | jq -r '.storage.disks[] | {id, device_id, device_path}'
> ```
> 
> during `validate_system_lxd` before we validate storage so that we can catch it if it happens again?

I'm all for it, short and useful output!

**Comment by masnax** [comment]
Not sure what's going on with the test, since it passes fine locally. 

I added a debug commit to cat the test logs to figure it out. The error seems to be on the interactive input, so maybe the debug binary isn't applying properly?

File: doc/how-to/initialise.rst [hunk 17]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
 
 See an example of the full initialisation process in the :ref:`Get started with MicroCloud <initialisation-process>` tutorial.
 
+Excluding MicroCeph or MicroOVN from MicroCloud
+-----------------------------------------------
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:94]:
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This section should be a subsection of "Interactive configuration", right?
Then we'll need to use another symbol for the heading (not sure about the length of the suggestion :wink: - should be as long as the title).

File: doc/how-to/initialise.rst [hunk 18]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+
+If the MicroOVN or MicroCeph snap is not installed on the system that runs :command:`microcloud init`, you will be prompted with the following question:
+
+  .. terminal::
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:98]:
```suggestion
If the MicroOVN or MicroCeph snap is not installed on the system that runs :command:`microcloud init`, you will be prompted with the following question::

```

No need for `terminal::` here - we use this when we want to show input and output. For only output, code style is sufficient.

File: doc/how-to/initialise.rst [hunk 19]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+     MicroCeph not found. Continue anyway? (yes/no) [default=yes]:
+
+     MicroOVN not found. Continue anyway? (yes/no) [default=yes]:
+
+  #. If you choose ``yes``,  only existing services will be configured on all systems.
+
+  #. If you choose ``no`` the setup will be aborted.
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:105]:
```suggestion
If you choose ``yes``, only existing services will be configured on all systems.
If you choose ``no``, the setup will be stopped.
```

No need for a list here imo, the paragraph is short enough. :)

File: doc/how-to/initialise.rst [hunk 20]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+
+All other systems must have at least the same set of snaps installed as the system that runs :command:`microcloud init`, otherwise they will not be available to select from the list of systems.
+Any questions associated to these systems will be skipped. For example, if MicroCeph is not installed, you will not be prompted for distributed storage configuration.
+
+Reusing an existing MicroCeph or MicroOVN with MicroCloud
+---------------------------------------------------------
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:111]:
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

File: doc/how-to/initialise.rst [hunk 21]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+
+If some of the systems are already part of a MicroCeph or MicroOVN cluster, you may reuse this cluster when initialising MicroCloud when prompted with the following question:
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:113]:
```suggestion
If some of the systems are already part of a MicroCeph or MicroOVN cluster, you can choose to reuse this cluster when initialising MicroCloud when prompted with the following question::
```

File: doc/how-to/initialise.rst [hunk 22]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+
+  .. terminal::
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:115]:
```suggestion
```

File: doc/how-to/initialise.rst [hunk 23]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+     "micro01" is already part of a MicroCeph cluster. Do you want to add this cluster to MicroCloud? (add/skip) [default=add]:
+
+     "micro01" is already part of a MicroOVN cluster. Do you want to add this cluster to MicroCloud? (add/skip) [default=add]:
+
+  #. If you choose ``add``, MicroCloud will add the remaining systems selected for initialisation to the pre-existing cluster.
+
+  #. If you choose ``skip``, MicroCloud will not configure the service to work with MicroCloud on any system.
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:122]:
```suggestion
If you choose ``add``, MicroCloud will add the remaining systems selected for initialisation to the pre-existing cluster.
If you choose ``skip``, MicroCloud will not configure the service to work with MicroCloud on any system.
```

Comment (ru-fu) [reply doc/how-to/initialise.rst:122]: If you choose skip, will MicroOVN/Ceph be set up in the usual way (forming a new cluster)? Or will it not be set up at all?
That's unclear from the description.

File: doc/how-to/initialise.rst [hunk 24]
```diff
@@ -90,6 +90,39 @@ Complete the following steps to initialise MicroCloud:
...
+
+If more than one MicroCeph or MicroOVN cluster exists among the systems, the MicroCloud initialisation will abort.
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:124]:
```suggestion
If more than one MicroCeph or MicroOVN cluster exists among the systems, the MicroCloud initialisation will be cancelled.
```

**Review by ru-fu — COMMENTED** [review]
Thanks! I think this is a good place for the information.
Just some general comments. :)

File: microcloud/test/suites/basic.sh [hunk 25]
```diff
@@ -822,3 +822,135 @@ test_auto() {
...
+  lxc exec micro03 -- microovn cluster bootstrap
+  microcloud_interactive | lxc exec micro01 -- sh -c "microcloud init > out"
+  services_validator
+
+  reset_systems 3 3 3
+  echo Create a MicroCloud that re-uses an existing existing service with multiple nodes from this cluster
+  export REUSE_EXISTING_COUNT=1
+  export REUSE_EXISTING="add"
+  lxc exec micro02 -- microceph cluster bootstrap
+  token="$(lxc exec micro02 -- microceph cluster add micro01)"
```
Comment (simondeziel) [inline microcloud/test/suites/basic.sh:892]: I didn't know`microceph` diverged in behavior from LXD where we need to pass `--quiet` to avoid showing the text header. Is that the case for `micro*`?

File: microcloud/test/suites/basic.sh [hunk 26]
```diff
@@ -822,3 +822,135 @@ test_auto() {
...
+  export SETUP_OVN="yes"
+  export OVN_FILTER="enp6s0"
+  export IPV4_SUBNET="10.1.123.1/24"
+  export IPV4_START="10.1.123.100"
+  export IPV4_END="10.1.123.254"
+  export DNS_ADDRESSES="10.1.123.1,8.8.8.8"
+  export IPV6_SUBNET="fd42:1:1234:1234::1/64"
+
+  reset_systems 3 3 3
+  echo Create a MicroCloud that re-uses an existing service
```
Comment (simondeziel) [inline microcloud/test/suites/basic.sh:858]: Could you quote the text after all those `echo`, please? IIRC, this helps the text highlighter in some IDEs.

File: microcloud/test/suites/basic.sh [hunk 27]
```diff
@@ -822,3 +822,135 @@ test_auto() {
...
+  lxc exec micro04 -- snap disable microcloud
+  lxc exec micro02 -- microceph cluster bootstrap
+  token="$(lxc exec micro02 -- microceph cluster add micro04)"
+  lxc exec micro04 -- microceph cluster join "${token}"
+  microcloud_interactive | lxc exec micro01 -- sh -c "microcloud init > out"
+  services_validator
+  validate_system_microceph micro04 1
+
+  reset_systems 3 3 3
+  echo Fail to create a MicroCloud due to an existing service if --auto specified
```
Comment (simondeziel) [inline microcloud/test/suites/basic.sh:918]: This is one good example where double quoting the string passed to `echo` would help the text highlighting because this `if` shows as a command instead of text. :)

File: microcloud/test/suites/basic.sh [hunk 28]
```diff
@@ -822,3 +822,135 @@ test_auto() {
...
+storage:
+  local:
+    - find: id == sdb
+      wipe: true
+  ceph:
+    - find: id == sdc
+      wipe: true
+  cephfs: true
+"
+  lxc exec micro01 -- sh -c "cat /root/preseed.yaml | TEST_CONSOLE=0 microcloud init --preseed"
```
Comment (simondeziel) [inline microcloud/test/suites/basic.sh:954]: Is the intermediate `/root/preseed.yaml` needed/useful for debugging? If not, would it be possible to use something like:
```
lxc exec micro01 --env TEST_CONSOLE=0 -- microcloud init --preseed << EOF

lookup_subnet: ${addr}/24
lookup_interface: enp5s0
reuse_existing_clusters: true
systems:
...
EOF
```

File: microcloud/test/suites/basic.sh (hunk 25 above)
Comment (masnax) [reply microcloud/test/suites/basic.sh:892]: the `micro*` projects don't have any header, they just spit out the token.

File: doc/how-to/initialise.rst (hunk 23 above)
Comment (masnax) [reply doc/how-to/initialise.rst:122]: Right, I meant that it won't be set up at all. 

How about:
`If you choose ``skip``, MicroCloud will ignore the service on all systems`?

Comment (ru-fu) [reply doc/how-to/initialise.rst:122]: Or maybe:
```
If you choose ``skip``, the respective service will not be set up at all.
```
"Ignoring the service" could also be interpreted as "ignoring the existing service/cluster".

File: doc/how-to/initialise.rst [hunk 29]
```diff
@@ -90,6 +90,37 @@ Complete the following steps to initialise MicroCloud:
...
+
+If the MicroOVN or MicroCeph snap is not installed on the system that runs :command:`microcloud init`, you will be prompted with the following question:
+
+     MicroCeph not found. Continue anyway? (yes/no) [default=yes]:
+
+     MicroOVN not found. Continue anyway? (yes/no) [default=yes]:
+
+  If you choose ``yes``,  only existing services will be configured on all systems.
+
+  If you choose ``no`` the setup will be cancelled.
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:104]:
```suggestion
    MicroCeph not found. Continue anyway? (yes/no) [default=yes]:

    MicroOVN not found. Continue anyway? (yes/no) [default=yes]:

If you choose ``yes``,  only existing services will be configured on all systems.
If you choose ``no``, the setup will be cancelled.
```

Too much indentation (must be 4 spaces afaik).
Also, missing comma in the last sentence, and I would combine the last two sentences into one paragraph (which means get rid of the empty line between them).

File: doc/how-to/initialise.rst [hunk 30]
```diff
@@ -90,6 +90,35 @@ Complete the following steps to initialise MicroCloud:
 
 See an example of the full initialisation process in the :ref:`Get started with MicroCloud <initialisation-process>` tutorial.
 
+Excluding MicroCeph or MicroOVN from MicroCloud
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+If the MicroOVN or MicroCeph snap is not installed on the system that runs :command:`microcloud init`, you will be prompted with the following question:
```
Comment (ru-fu) [inline doc/how-to/initialise.rst:96]:
```suggestion
If the MicroOVN or MicroCeph snap is not installed on the system that runs :command:`microcloud init`, you will be prompted with the following question::
```

Sorry, missed that in my previous review. I had it in my first one though. :stuck_out_tongue_closed_eyes: 
You need two colons to introduce a code block.

Same change below as well.

**Comment by masnax** [comment]
@roosterfish @tomponline Could one of you please look this over one last time before merging? Thanks!

**Comment by masnax** [comment]
> > (That 1 test failure is an issue with the test suite being too hard on the runners, it passes consistently when run locally).
> 
> @masnax does this mean if we merge this we will get that test failing going forward then?
> 
> If so then thats a merge blocker to me.

The test will be just as flaky on any PR regardless of if this one is merged. The test was not affected by this PR, the issue is that we just can't consistently run 4 VMs on the github runners without them running into issues like LXD being unable to start up.

**Comment by tomponline** [comment]
I see @masnax thanks for clarifying that. It sounded like this PR was introducing the tests that were flaky.

I'll leave the final review to @roosterfish

File: microcloud/cmd/microcloud/main_init.go [hunk 31]
```diff
@@ -532,6 +539,83 @@ func validateSystems(s *service.Handler, systems map[string]InitSystem) (err err
...
+		for k, v := range remoteClusterMembers {
+			host, _, err := net.SplitHostPort(v)
+			if err != nil {
+				return "", nil, err
+			}
+
+			clusterMembers[k] = host
+		}
+
+		if autoSetup {
```
Comment (roosterfish) [inline microcloud/cmd/microcloud/main_init.go:646]: As `autoSetup` doesn't get modified in this func, would it be a better choice not passing this var into `checkClustered` and performing the check outside?

File: microcloud/cmd/microcloud/main_init.go [hunk 32]
```diff
@@ -369,61 +375,117 @@ func waitForJoin(sh *service.Handler, clusterSize int, secret string, peer strin
...
+	// If the local node needs to join an existing cluster, do it first so we can proceed as normal.
+	if len(joinConfig[sh.Name].Tokens) > 0 {
+		cfg := joinConfig[sh.Name]
+		err := waitForJoin(sh, clusterSize, "", sh.Name, cfg)
+		if err != nil {
+			return err
+		}
+
+		// Sleep 3 seconds to give the cluster roles time to reshuffle before adding more members.
+		time.Sleep(3 * time.Second)
```
Comment (roosterfish) [inline microcloud/cmd/microcloud/main_init.go:475]: I can remember this raised my attention the last time when reviewing it.

As this pattern is used at other places this shouldn't be a blocker but would it be another option retrying the "adding more members" operations instead with a timeout in case it doesn't work?

File: microcloud/service/microcloud.go (hunk 10 above)
Comment (roosterfish) [reply microcloud/service/microcloud.go:150]: Ok so https://github.com/canonical/microcloud/pull/287 has to come after this one then?

File: microcloud/test/suites/basic.sh [hunk 33]
```diff
@@ -822,3 +822,134 @@ test_auto() {
...
+  export REUSE_EXISTING_COUNT=1
+  export REUSE_EXISTING="add"
+  lxc exec micro02 -- microceph cluster bootstrap
+  token="$(lxc exec micro02 -- microceph cluster add micro01)"
+  lxc exec micro01 -- microceph cluster join "${token}"
+  microcloud_interactive | lxc exec micro01 -- sh -c "microcloud init > out"
+  services_validator
+
+  reset_systems 3 3 3
+  echo "Create a MicroCloud that re-uses an existing existing service with all nodes from this cluster"
```
Comment (roosterfish) [inline microcloud/test/suites/basic.sh:898]: Two times `existing`.

**Review by roosterfish — CHANGES_REQUESTED** [review]
Just a few more small comments, rest still looking good to me.

File: microcloud/api/types/services.go [hunk 34]
```diff
@@ -36,3 +36,9 @@ type ServiceToken struct {
 	Service   ServiceType `json:"service" yaml:"service"`
 	JoinToken string      `json:"join_token" yaml:"join_token"`
 }
+
+// ServiceTokensPost represents a request to issue a join token for a MicroCloud service.
+type ServiceTokensPost struct {
+	ClusterAddress string `json:"cluster_address" yaml:"cluster_address"`
+	JoinerName     string `json:"joiner_name"     yaml:"joiner_name"`
```
[the remark this answers is not in the document]
Comment (masnax) [reply microcloud/api/types/services.go:43]: No it won't become obsolete, the name is used to identify the secret join key in the issuer's database. The change in microcluster removed the name only from the base64 encoded payload which included the secret key and the join addresses: https://github.com/canonical/microcluster/blob/ceb18595e3c6e75150d1a5106a6b363082a1c794/internal/rest/types/tokens.go#L11-L28

You should see the first struct still has a `Name` field.

File: microcloud/cmd/microcloud/main_init.go (hunk 32 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:475]: This is here because retrying the connection too quickly can result in dqlite locking up and you would get hit with a `context deadline exceeded` error. 

This was mainly an issue with LXD's dqlite implementation which I've since addressed, but I haven't gotten around to testing if I can safely remove these timeouts in MicroCloud. I'll file an issue for this, thanks for reminding me.

File: microcloud/cmd/microcloud/main_init.go (hunk 31 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:646]: It's just for efficiency. We can move it outside but that would mean that we would have to run through the rest of `checkClustered`'s implementation. Where it is now, as soon as at least 1 system gets to this point, we can exit if `autoSetup` is true, rather than continuing to build the list and checking more systems, only to error out afterward anyway.

File: microcloud/cmd/microcloud/main_init.go (hunk 32 above)
Comment (roosterfish) [reply microcloud/cmd/microcloud/main_init.go:475]: Right makes sense.

File: microcloud/api/types/services.go (hunk 34 above)
[the remark this answers is not in the document]
Comment (roosterfish) [reply microcloud/api/types/services.go:43]: Right makes sense.

File: microcloud/cmd/microcloud/main_init.go (hunk 32 above)
Comment (roosterfish) [reply microcloud/cmd/microcloud/main_init.go:475]: Ah sorry I think I got distracted reviewing whilst trying to lookup the issue. Have you logged it in another repo?

**Review by roosterfish — APPROVED** [review]

File: microcloud/cmd/microcloud/main_init.go (hunk 32 above)
Comment (masnax) [reply microcloud/cmd/microcloud/main_init.go:475]: Instead of that I'm just working on a PR to remove them :)

Comment (roosterfish) [reply microcloud/cmd/microcloud/main_init.go:475]: Cool, thanks!
