### PR TITLE
cmd/microcloud: Fix user confirmation for missing services

### LINKED ISSUE #146: User cannot abort init process if any service is missing
If any services, such as MicroCeph and MicroOVN, are missing when MicroCloud is being initialized,
user cannot abort the process.

Regardless of the user's response, the process always continues normally:
```
Limit search for other MicroCloud servers to 10.45.149.211/24? (yes/no) [default=yes]: yes 
MicroCeph,MicroOVN not found. Continue anyway? (yes/no) [default=yes]: yes
Scanning for eligible servers ...

Limit search for other MicroCloud servers to 10.45.149.211/24? (yes/no) [default=yes]: yes 
MicroCeph,MicroOVN not found. Continue anyway? (yes/no) [default=yes]: no
Scanning for eligible servers ...
```

### PR DESCRIPTION
**Pull request by MusicDin**
Return an error if user does not confirm to continue with missing services.

Fixes #146

### CODE REVIEW

File: microcloud/cmd/microcloud/ask.go [hunk 1]
```diff
@@ -52,16 +52,18 @@ func askMissingServices(services []types.ServiceType, stateDirs map[types.Servic
...
-			skip, err := cli.AskBool(fmt.Sprintf("%s not found. Continue anyway? (yes/no) [default=yes]: ", serviceStr), "yes")
+			confirm, err := cli.AskBool(fmt.Sprintf("%s not found. Continue anyway? (yes/no) [default=yes]: ", serviceStr), "yes")
 			if err != nil {
 				return nil, err
 			}
 
-			if !skip {
-				return services, nil
+			if !confirm {
+				return nil, fmt.Errorf("User aborted.")
```
Comment (tomponline) [inline microcloud/cmd/microcloud/ask.go:63]: We dont include full stops in errors.

**Review by masnax — APPROVED** [review]
Thanks for this! :)
