### PR TITLE
Autocomplete fixes

### LINKED ISSUE #959: Autocomplete model doesn't recognize newline on copy & paste
Before having the autocomplete model for typing the passphrase, you could simply copy & paste the passphrase including a newline from the initiator and continue on the joiner by pasting the passphrase which then already submitted the passphrase without having the need to press the enter/return key.

In the new model this newline isn't considered anymore and you have to paste and press the enter key. 
The autocomplete model should recognize the newline and proceed further if encountered. This is due to convenience and to keep the old behavior.

### PR DESCRIPTION
**Pull request by kadinsayani**
Closes #959.

### CODE REVIEW

File: cmd/microcloud/session.go [hunk 1]
```diff
@@ -85,12 +85,11 @@ func (c *initConfig) initiatingSession(gw *cloudClient.WebsocketGateway, sh *ser
 When requested, enter the passphrase:
 
  %s
-
 Verify the fingerprint %s is displayed on joining systems.
 `
 
 		cmdArg := tui.Fmt{Arg: "microcloud join", Color: tui.Green, Bold: true}
-		passArg := tui.Fmt{Arg: session.Passphrase, Color: tui.Green, Bold: true}
+		passArg := tui.Fmt{Arg: session.Passphrase + "\n", Color: tui.Green, Bold: true}
```
Comment (roosterfish) [inline cmd/microcloud/session.go]: Isn't it the same as leaving the newline under the `%s` in the template?

File: cmd/tui/autocomplete.go [hunk 2]
```diff
@@ -45,10 +45,12 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
 	case tea.KeyMsg:
 		switch msg.Type {
-		case tea.KeyEnter, tea.KeyCtrlC, tea.KeyEsc:
+		case tea.KeyEnter, tea.KeyCtrlJ:
 			m.textInput.Blur()
 			return m, tea.Quit
-
+		case tea.KeyCtrlC, tea.KeyEsc:
+			m.textInput.SetValue("")
+			return m, tea.Quit
```
Comment (roosterfish) [inline cmd/tui/autocomplete.go]: We have to return something else than `tea.Quit` to allow Ctrl+c to exit the `microcloud join` command. Otherwise you end up in a situation where you have to type in the password, otherwise you cannot exit out as the passphrase never matches the validator.

Just checked what other `tea` messages are there, what about `tea.Interrupt`? We need something that produces a non nil error so that we exit out of this retry loop. 
Maybe we can catch the error and just quit to resemble the same behavior as with regular text inputs (e.g. yes/no) which also just quits when you press CTRL+c.

File: cmd/tui/autocomplete.go [hunk 3]
```diff
@@ -44,6 +44,18 @@ func (m model) Init() tea.Cmd {
 func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 	switch msg := msg.(type) {
 	case tea.KeyMsg:
+		// Auto-submit if a paste contains ends with newline.
```
Comment (roosterfish) [inline cmd/tui/autocomplete.go]: Was giving it a try but it doesn't work for me so let me try to explain you what is currently working in `2/stable`.

You can left click three times to highlight and select the entire row (which contains a newline):

Screenshot from 2025-09-09 09-54-01

Then when you paste the passphrase on one of the joiners, its submitting the text input right away as it contains a newline:

Screenshot from 2025-09-09 09-55-10

Maybe this extra whitespace in front of the first word of the passphrase is setting it off?

**Review by roosterfish — CHANGES_REQUESTED** [review]
Thanks for taking a look at this so quickly. Please check my comments, maybe I am missing something.

File: cmd/tui/autocomplete.go (hunk 2 above)
Comment (kadinsayani) [reply cmd/tui/autocomplete.go]: `tea.Interrupt` works well, thanks for the suggestion!

image

File: cmd/microcloud/session.go (hunk 1 above)
Comment (kadinsayani) [reply cmd/microcloud/session.go]: Yes, it should be. However, the `\n` was not being picked up unless appended to `session.Passphrase` when we set `Arg`. 

I think this actually has to do with my terminal emulator stripping the `\n` when selecting text. The `\n` is only detected when I explicitly include an empty line like this:

image

File: cmd/tui/autocomplete.go (hunk 3 above)
Comment (kadinsayani) [reply cmd/tui/autocomplete.go]: Due to observed inconsistencies across terminal emulators when selecting text containing `\n` characters, I'm going to rework this PR to follow a different approach. I think we can either simulate a null-terminated C style string by appending `\x00`, or count the number of words and auto-submit if they match `PassphraseWordCount` (4).

Comment (kadinsayani) [reply cmd/tui/autocomplete.go]: On second thought, to avoid complicating things and running into edge cases for different terminal emulators, we can just auto-submit the trimmed input on paste, regardless of string content. This will suffice because we already print errors and allow for retries when a passphrase is incomplete (<4 words) or incorrect.

File: cmd/microcloud/session.go (hunk 1 above)
Comment (roosterfish) [reply cmd/microcloud/session.go]: Ah ok that is interesting. I was only testing this with the regular terminal on my Ubuntu system.

File: cmd/tui/autocomplete.go (hunk 2 above)
Comment (roosterfish) [reply cmd/tui/autocomplete.go]: Should we omit the `program was killed: ...` text and simply exit out? If you for example quit any of the other text inputs we also don't print any extra error message for Ctrl+c:

```bash
root@micro03:~# microcloud init
Waiting for services to start ...
Do you want to set up more than one cluster member? (yes/no) [default=yes]: ^C
```

Maybe there is a specific error type you can catch using `errors.Is` and simply exit.

File: cmd/tui/autocomplete.go (hunk 3 above)
Comment (roosterfish) [reply cmd/tui/autocomplete.go]: That sounds practical, thanks!

File: cmd/tui/autocomplete.go (hunk 2 above)
Comment (kadinsayani) [reply cmd/tui/autocomplete.go]: Sounds good! We can exit on `errors.Is(err, tea.ErrInterrupted)`.

**Review by roosterfish — APPROVED** [review]
Thanks!
